apiVersion: v1
kind: Service
metadata:
  name: order-generator
  labels:
    app: order-generator
spec:
  selector:
    app: order-generator
  ports:
    - port: 8080
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-generator-v1
  labels:
    app: order-generator
    version: v1
spec:
  selector:
    matchLabels:
      app: order-generator
  replicas: 1
  template:
    metadata:
      labels:
        app: order-generator
        version: v1
    spec:
      containers:
        - name: order-generator
          image: evanschan/order-generator:latest
          ports:
            - containerPort: 8080